### ISSUE TITLE
OBS not detecting FFmpeg with nvenc

### ISSUE THREAD

**Issue by jankyjames** [omen23/ffmpeg-ffnvcodec-explanation#3]
I am missing two items when I run ffmpeg -hide_banner -hwaccels. Not sure if thats an issue

vaapi
drm

Everything else is installed correctly, using your verification steps.

OBS only shows software encoding

**Comment by omen23** [comment]
is your card supported ?  send me the output when you launch `obs` from a terminal emulator.
```
info: No blackmagic support
info: NVENC supported
info: FFMPEG VAAPI supported
info: VLC found, VLC video source enabled
info: ---------------------------------
info:   Loaded Modules:
info:     libobs-linuxbrowser.so
info:     vlc-video.so
info:     text-freetype2.so
info:     rtmp-services.so
info:     obs-x264.so
info:     obs-transitions.so
info:     obs-outputs.so
info:     obs-libfdk.so
info:     obs-filters.so
info:     obs-ffmpeg.so
info:     linux-v4l2.so
info:     linux-pulseaudio.so
info:     linux-jack.so
info:     linux-decklink.so
info:     linux-capture.so
info:     linux-alsa.so
info:     image-source.so
info:     frontend-tools.so
info:     decklink-ouput-ui.so
```
if you miss drm and vaapi, you cant have direct rendering enabled - maybe reinstall your graphics cards drivers and tell me what card you are using.

**Comment by jankyjames** [comment]
It's a 1080ti, pretty sure

**Comment by omen23** [comment]
without the debug output I cant help you!!

**Comment by omen23** [comment]
I will close this issue until there is more information available.
