### ISSUE TITLE
Warnings in .DEB creation

### ISSUE THREAD

**Issue by eddiecsilva** [omen23/ffmpeg-ffnvcodec-explanation#5]
Thanks so much for sharing this information, when trying to perform this procedure on Ubuntu 19.10 beta at the end of creating the DEB packages I get a message that 1 error and 7 warnings occurred.

The packages are generated and I can complete the installation without any problems, but I would like to know if these messages can be handled.

How can I check for these errors and warnings?

**Comment by catb0t** [comment]
Those are small errors/anomalies in FFmpeg's man pages and build scripts. Like FFmpeg's C compiler warnings that you see when making, they're not a big problem (sometimes even intentional or a bug in `lintian`), and when they are a problem, they're only able to be fixed with upstream patches.

**Comment by omen23** [comment]
Can you just output when these errors are generated in the build process and copy them and post them here. When do they happen - like before entering `sudo dpkg -i *.deb` or after - normally no errors should occur in the build process, not even of the C dynamic binaries (`ffmpeg ffprobe ffplay`) nor the shared libraries 
```
libavutil      56. 22.100 / 56. 22.100
libavcodec     58. 35.100 / 58. 35.100
libavformat    58. 20.100 / 58. 20.100
libavdevice    58.  5.100 / 58.  5.100
libavfilter     7. 40.101 /  7. 40.101
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  3.100 /  5.  3.100
libswresample   3.  3.100 /  3.  3.100
libpostproc    55.  3.100 / 55.  3.100
```
Kind Regards

**Comment by omen23** [comment]
@catb0t I think he has the `extra*` problem. Idk I might be on the completely wrong tracks and it is all about the **actual** compilation process.

**Comment by eddiecsilva** [comment]
Thank all of you for the informations.

The distributions where I tested the installation process were environment already in production and with a lot of programs installed, I intend to test in a clean installation.

Not sure if this influences, but my GPU is a GTX 1650 4Gb on an AMD Ryzen 5 platform.

> @catb0t I think he has the `extra*` problem. Idk I might be on the completely wrong tracks and it is all about the **actual** compilation process.

You're right, when trying to install the packages I had problems with `libavcodec-extra58` and had to remove it manually.

**Comment by catb0t** [comment]
Sorry, I thought you were referring to the errors at the end of `debuild`, where it says "7 warnings" from `lintian`.

**Comment by omen23** [comment]
SO everything working now? then closed.
